### ISSUE TITLE
Race condition

### ISSUE THREAD

**Issue by tdunning** [anthonyu/KeptCollections#1]
The update in KeptMap has a race condition:

 <code>
if (this.map.containsKey(key)) {
    String oldval = this.get(key);
    this.keeper.setData(path, value.getBytes(), -1);
    return oldval;
    } else {
    this.keeper.create(path, value.getBytes(), this.acl, this.createMode);
    return null;
    }
</code>

can fail easily in the presence of simultaneous updates.  It is better to do the create, catch NodeExists and then do an update and return.  This can be wrapped in a loop to catch the complementary race condition versus deletions.

**Comment by anthonyu** [comment]
Thanks for the report.  This is fixed in <a href="https://github.com/anthonyu/KeptCollections/commit/b9ce3c61b03a6e21d6c6b77b443901e55d61390b">b9ce3c6</a>
