### ISSUE TITLE
More relaxed implementation for KeptBlockingQueue

### ISSUE THREAD

**Issue by alexey-sakolski** [anthonyu/KeptCollections#10]
More relaxed implementation for KeptBlockingQueue
As I understand, the current implementation of KeptBlockingQueue is asynchronously reread the whole queue form ZK after each change of queue is performed. Despite the fact that ZK can join some events, the number of rereads is huge, and, moreover, the asymptotic on transfer data is O(N*N) and that is very painful if we start to process non empty queue. 
It seems, the implementation can't be radically improved, due to luck of some features in ZK API (getFirstChild, for example) but it possible to make a more "relaxed" implementation, that is will be not fully conform to java Collections API, but will be have better performance.
For example, if we sacrifice the size() method accuracy, we can process BlockingQueue by batches, and perform new read from ZK only when we process all previously read query items. That is can radically
improve performance, at least, for low-consumer-number scenario.

**Comment by otisg** [comment]
@anthonyu what are your thoughts on this?  Is this something you could implement?  We are using KC in production and our performance is starting to suffer because of the above.  Thanks!

**Comment by anthonyu** [comment]
I approve of this.  Do you have a fix already?  If not, I can play with it this weekend.

**Comment by otisg** [comment]
@anthonyu Woohoo, great to hear.  We're currently a bit busy, so if you have time for it now, please go for it!  We'd be happy to give your new code a try and let you know ho wit works for us.

**Comment by anthonyu** [comment]
I have committed a class called UnkemptBlockingQueue that very lazily caches the remote data, but still should be just as consistent as KeptBlockingQueue.  Give it a try, if it improves your performance sufficiently enough, and seems to work correctly, perhaps we can replace the original semantics with these new lazy ones.

**Comment by otisg** [comment]
@anthonyu Spelling note: unkempt => unkept (both in package and class name)

**Comment by anthonyu** [comment]
That's intentional.

**Comment by otisg** [comment]
@anthonyu Interesting - what's the intention?  To show that something is "unorthodocks", or? :)

**Comment by anthonyu** [comment]
Well, it's just a philosophical difference between the two methods.  The
new method uses a delayed-synchronization cache methodology that just feels
unkempt to me.

Cheers,
Anthony

**Comment by anthonyu** [comment]
I'm guessing my last commit was satisfactory.

**Comment by otisg** [comment]
Thanks @anthonyu !
