### ISSUE TITLE
Publish to a maven repo?

### ISSUE THREAD

**Issue by tdunning** [anthonyu/KeptCollections#11]
Any chance that Kept Collections will be available in a maven repo?

For that matter, is Kept Collections still alive?

**Comment by anthonyu** [comment]
> Any chance that Kept Collections will be available in a maven repo?

Sure, I'll look into it this weekend.

> For that matter, is Kept Collections still alive?

It's in active use by at least two companies that I have done work for, but I don't think there is any more coding to be done to it: I am not aware of any bugs, and don't personally need it to do anything it doesn't already do.  Did you have a feature suggestion?

**Comment by mwielbut** [comment]
Hey Anthony, any luck on pushing this to a maven repo so we can just pull the jar as a remote dependency?

**Comment by anthonyu** [comment]
Here you go:

https://oss.sonatype.org/index.html#nexus-search;quick~keptcollections
