### ISSUE TITLE
the second infinite loop

### ISSUE THREAD

**Issue by d0ngw** [anthonyu/KeptCollections#6]
And the i variable is always 0 too.

private String removeUnsynchronized(Object key) throws InterruptedException, KeeperException {

String path = this.znode + '/' + key;

try {
    Stat stat = new Stat();
    int i = 0;

```
while (true) {
try {
    byte[] oldval = this.keeper.getData(path, false, stat);

    this.keeper.delete(path, stat.getVersion());

    return new String(oldval);
} catch (KeeperException.BadVersionException e) {
    if (i > 10)
    throw e;

    // someone updated it in between, try again
    KeptMap.LOG
        .debug("caught bad version attempting to update, retrying");

    Thread.sleep(50);
}
}
```

} catch (KeeperException.NoNodeException e) {
    return null;
}

**Comment by anthonyu** [comment]
OK, this is patched and will go out soon.
